# Setting Up the Environment for Web Scraping

In [3]:
#!pip install bs4 # BeautifulSoup allows us to parse the page
#!pip install requests # requests allows us to make http request and extract data from the page

In [4]:
import pandas as pd
import requests
pd.set_option('display.max_columns', None) # so we can see all columns in a wide DataFrame
import time
import numpy as np

# Defining the URL for Web Scraping

In [5]:
test_url = "https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=PerGame&Scope=S&Season=2024-25&SeasonType=Regular%20Season&StatCategory=PTS"

# Fetching and Parsing JSON Data from the NBA Stats Website

In [6]:
r = requests.get(url=test_url).json()

In [7]:
table_headers = r['resultSet']['headers']

In [8]:
pd.DataFrame(r['resultSet']['rowSet'], columns=table_headers)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PTS,EFF
0,1628983,1,Shai Gilgeous-Alexander,1610612760,OKC,60,34.2,11.2,21.4,0.525,2.1,5.7,0.374,8.0,9.0,0.896,0.9,4.2,5.2,6.2,1.8,1.0,2.5,32.6,33.2
1,203507,2,Giannis Antetokounmpo,1610612749,MIL,48,34.1,12.2,20.2,0.604,0.2,0.9,0.190,6.2,10.4,0.591,2.2,9.8,12.1,6.0,0.8,1.3,3.3,30.8,35.2
2,203999,3,Nikola Jokić,1610612743,DEN,55,36.1,11.0,19.1,0.578,2.0,4.4,0.443,4.9,6.0,0.822,2.9,9.9,12.7,10.4,1.8,0.7,3.3,28.9,42.2
3,1630162,4,Anthony Edwards,1610612750,MIN,60,36.5,9.1,20.6,0.439,4.1,10.1,0.405,5.2,6.2,0.842,0.8,5.2,6.0,4.6,1.2,0.6,3.4,27.4,23.8
4,1628369,5,Jayson Tatum,1610612738,BOS,58,36.5,9.1,20.1,0.452,3.6,10.1,0.352,5.0,6.3,0.802,0.7,8.2,8.8,5.8,1.1,0.5,2.9,26.8,27.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,1641748,241,Andre Jackson Jr.,1610612749,MIL,54,16.5,1.5,3.2,0.469,0.5,1.3,0.386,0.2,0.3,0.556,1.1,2.0,3.0,1.4,0.6,0.2,0.9,3.7,6.1
241,201587,242,Nicolas Batum,1610612746,LAC,58,17.0,1.1,2.8,0.388,0.9,2.4,0.384,0.2,0.3,0.813,0.6,2.1,2.7,1.2,0.7,0.4,0.4,3.3,6.1
242,201599,243,DeAndre Jordan,1610612743,DEN,46,11.5,1.5,2.3,0.651,0.0,0.0,0.000,0.3,0.8,0.405,1.4,3.3,4.7,0.8,0.3,0.4,0.7,3.3,7.5
243,1642345,244,Oso Ighodaro,1610612756,PHX,44,13.8,1.4,2.5,0.574,0.0,0.0,0.000,0.4,0.8,0.528,0.8,2.3,3.0,0.9,0.4,0.3,0.5,3.3,6.0
244,1630579,245,Jericho Sims,1610612749,MIL,46,11.5,0.7,1.2,0.596,0.0,0.0,0.000,0.2,0.3,0.615,1.3,2.2,3.4,0.6,0.2,0.3,0.6,1.7,4.9

# Creating and Structuring the Initial DataFrame

In [9]:
temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns=table_headers)

In [10]:
temp_df2 = pd.DataFrame({'Year':['2000-01' for i in range(len(temp_df1))],
                        'Season_type':['Regular%20Season' for i in range(len(temp_df1))]})
temp_df3 = pd.concat([temp_df2,temp_df1], axis=1)
temp_df3

,Year,Season_type,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PTS,EFF
0,2000-01,Regular%20Season,1628983,1,Shai Gilgeous-Alexander,1610612760,OKC,60,34.2,11.2,21.4,0.525,2.1,5.7,0.374,8.0,9.0,0.896,0.9,4.2,5.2,6.2,1.8,1.0,2.5,32.6,33.2
1,2000-01,Regular%20Season,203507,2,Giannis Antetokounmpo,1610612749,MIL,48,34.1,12.2,20.2,0.604,0.2,0.9,0.190,6.2,10.4,0.591,2.2,9.8,12.1,6.0,0.8,1.3,3.3,30.8,35.2
2,2000-01,Regular%20Season,203999,3,Nikola Jokić,1610612743,DEN,55,36.1,11.0,19.1,0.578,2.0,4.4,0.443,4.9,6.0,0.822,2.9,9.9,12.7,10.4,1.8,0.7,3.3,28.9,42.2
3,2000-01,Regular%20Season,1630162,4,Anthony Edwards,1610612750,MIN,60,36.5,9.1,20.6,0.439,4.1,10.1,0.405,5.2,6.2,0.842,0.8,5.2,6.0,4.6,1.2,0.6,3.4,27.4,23.8
4,2000-01,Regular%20Season,1628369,5,Jayson Tatum,1610612738,BOS,58,36.5,9.1,20.1,0.452,3.6,10.1,0.352,5.0,6.3,0.802,0.7,8.2,8.8,5.8,1.1,0.5,2.9,26.8,27.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,2000-01,Regular%20Season,1641748,241,Andre Jackson Jr.,1610612749,MIL,54,16.5,1.5,3.2,0.469,0.5,1.3,0.386,0.2,0.3,0.556,1.1,2.0,3.0,1.4,0.6,0.2,0.9,3.7,6.1
241,2000-01,Regular%20Season,201587,242,Nicolas Batum,1610612746,LAC,58,17.0,1.1,2.8,0.388,0.9,2.4,0.384,0.2,0.3,0.813,0.6,2.1,2.7,1.2,0.7,0.4,0.4,3.3,6.1
242,2000-01,Regular%20Season,201599,243,DeAndre Jordan,1610612743,DEN,46,11.5,1.5,2.3,0.651,0.0,0.0,0.000,0.3,0.8,0.405,1.4,3.3,4.7,0.8,0.3,0.4,0.7,3.3,7.5
243,2000-01,Regular%20Season,1642345,244,Oso Ighodaro,1610612756,PHX,44,13.8,1.4,2.5,0.574,0.0,0.0,0.000,0.4,0.8,0.528,0.8,2.3,3.0,0.9,0.4,0.3,0.5,3.3,6.0
244,2000-01,Regular%20Season,1630579,245,Jericho Sims,1610612749,MIL,46,11.5,0.7,1.2,0.596,0.0,0.0,0.000,0.2,0.3,0.615,1.3,2.2,3.4,0.6,0.2,0.3,0.6,1.7,4.9

In [11]:
del temp_df1, temp_df2, temp_df3

In [12]:
df_cols = ['Year', 'Season_type'] + table_headers

In [13]:
pd.DataFrame(columns=df_cols)

Empty DataFrame
Columns: [Year, Season_type, PLAYER_ID, RANK, PLAYER, TEAM_ID, TEAM, GP, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TOV, PTS, EFF]
Index: []

# Setting Up HTTP Request Headers

# Looping Through Seasons and Playoff Data to Scrape NBA Statistics

In [16]:
df = pd.DataFrame(columns=df_cols)
season_types = ['Regular%20Season', 'Playoffs']
years = ['2000-01','2001-02','2002-03','2003-04','2004-05','2005-06','2006-07','2007-08','2008-09','2009-10',
         '2010-11','2011-12','2012-13','2013-14','2014-15','2015-16','2016-17','2017-18','2018-19','2020-21',
         '2021-22','2022-23','2023-24','2024-25']

begin_loop = time.time()

for y in years:
    for s in season_types:
        api_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=PerGame&Scope=S&Season='+y+'&SeasonType='+s+'&StatCategory=PTS'
        r = requests.get(url=api_url).json()
        temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns=table_headers)
        temp_df2 = pd.DataFrame({'Year':[y for i in range(len(temp_df1))],
                                'Season_type':[s for i in range(len(temp_df1))]})
        temp_df3 = pd.concat([temp_df2,temp_df1],axis=1)
        df = pd.concat([df,temp_df3], axis=0)
        print(f'Finished Scraping data for the {y} {s}.')
        #delay loop, so nba doesnt thing we are a bot
        lag = np.random.uniform(low=0,high=5)
        print(f'...waiting {round(lag,1)} seconds')
        time.sleep(lag) 
print(f'Process Completed! Total run time: {round((time.time()-begin_loop)/60,2)}')
df.to_excel('nba_player_data.xlsx',index=False)

Finished Scraping data for the 2000-01 Regular%20Season.
...waiting 1.8 seconds
Finished Scraping data for the 2000-01 Playoffs.
...waiting 0.4 seconds
Finished Scraping data for the 2001-02 Regular%20Season.
...waiting 0.6 seconds
Finished Scraping data for the 2001-02 Playoffs.
...waiting 0.4 seconds
Finished Scraping data for the 2002-03 Regular%20Season.
...waiting 2.5 seconds
Finished Scraping data for the 2002-03 Playoffs.
...waiting 4.7 seconds
Finished Scraping data for the 2003-04 Regular%20Season.
...waiting 3.9 seconds
Finished Scraping data for the 2003-04 Playoffs.
...waiting 0.3 seconds
Finished Scraping data for the 2004-05 Regular%20Season.
...waiting 1.6 seconds
Finished Scraping data for the 2004-05 Playoffs.
...waiting 4.8 seconds
Finished Scraping data for the 2005-06 Regular%20Season.
...waiting 1.7 seconds
Finished Scraping data for the 2005-06 Playoffs.
...waiting 2.3 seconds
Finished Scraping data for the 2006-07 Regular%20Season.
...waiting 0.9 seconds
Finished Scraping data for the 2006-07 Playoffs.
...waiting 4.5 seconds
Finished Scraping data for the 2007-08 Regular%20Season.
...waiting 0.0 seconds
Finished Scraping data for the 2007-08 Playoffs.
...waiting 2.6 seconds
Finished Scraping data for the 2008-09 Regular%20Season.
...waiting 4.3 seconds
Finished Scraping data for the 2008-09 Playoffs.
...waiting 4.8 seconds
Finished Scraping data for the 2009-10 Regular%20Season.
...waiting 4.9 seconds
Finished Scraping data for the 2009-10 Playoffs.
...waiting 3.4 seconds
Finished Scraping data for the 2010-11 Regular%20Season.
...waiting 2.2 seconds
Finished Scraping data for the 2010-11 Playoffs.
...waiting 4.9 seconds
Finished Scraping data for the 2011-12 Regular%20Season.
...waiting 3.1 seconds
Finished Scraping data for the 2011-12 Playoffs.
...waiting 2.7 seconds
Finished Scraping data for the 2012-13 Regular%20Season.
...waiting 0.6 seconds
Finished Scraping data for the 2012-13 Playoffs.
...waiting 3.2 seconds
Finished Scraping data for the 2013-14 Regular%20Season.
...waiting 3.8 seconds
Finished Scraping data for the 2013-14 Playoffs.
...waiting 3.5 seconds
Finished Scraping data for the 2014-15 Regular%20Season.
...waiting 2.6 seconds
Finished Scraping data for the 2014-15 Playoffs.
...waiting 2.1 seconds
Finished Scraping data for the 2015-16 Regular%20Season.
...waiting 3.3 seconds
Finished Scraping data for the 2015-16 Playoffs.
...waiting 3.5 seconds
Finished Scraping data for the 2016-17 Regular%20Season.
...waiting 1.3 seconds
Finished Scraping data for the 2016-17 Playoffs.
...waiting 0.1 seconds
Finished Scraping data for the 2017-18 Regular%20Season.
...waiting 3.0 seconds
Finished Scraping data for the 2017-18 Playoffs.
...waiting 0.9 seconds
Finished Scraping data for the 2018-19 Regular%20Season.
...waiting 0.3 seconds
Finished Scraping data for the 2018-19 Playoffs.
...waiting 3.8 seconds
Finished Scraping data for the 2020-21 Regular%20Season.
...waiting 0.0 seconds
Finished Scraping data for the 2020-21 Playoffs.
...waiting 3.7 seconds
Finished Scraping data for the 2021-22 Regular%20Season.
...waiting 0.4 seconds
Finished Scraping data for the 2021-22 Playoffs.
...waiting 4.1 seconds
Finished Scraping data for the 2022-23 Regular%20Season.
...waiting 4.1 seconds
Finished Scraping data for the 2022-23 Playoffs.
...waiting 2.3 seconds
Finished Scraping data for the 2023-24 Regular%20Season.
...waiting 2.1 seconds
Finished Scraping data for the 2023-24 Playoffs.
...waiting 2.0 seconds
Finished Scraping data for the 2024-25 Regular%20Season.
...waiting 0.7 seconds
Finished Scraping data for the 2024-25 Playoffs.
...waiting 1.4 seconds
Process Completed! Total run time: 2.41

In [21]:
# load the file
file_path = "../data/nba_player_data.xlsx"
df = pd.read_excel(file_path)

# first few rows
df.head()

,Year,Season_type,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PTS,EFF
0,2000-01,Regular%20Season,947,1,Allen Iverson,1610612755,PHI,71,42.0,10.7,25.5,0.420,1.4,4.3,0.320,8.2,10.1,0.814,0.7,3.1,3.8,4.6,2.5,0.3,3.3,31.1,22.3
1,2000-01,Regular%20Season,711,2,Jerry Stackhouse,1610612765,DET,80,40.2,9.7,24.1,0.402,2.1,5.9,0.351,8.3,10.1,0.822,1.2,2.7,3.9,5.1,1.2,0.7,4.1,29.8,20.4
2,2000-01,Regular%20Season,406,3,Shaquille O'Neal,1610612747,LAL,74,39.5,11.0,19.2,0.572,0.0,0.0,0.000,6.7,13.1,0.513,3.9,8.8,12.7,3.7,0.6,2.8,2.9,28.7,31.0
3,2000-01,Regular%20Season,977,4,Kobe Bryant,1610612747,LAL,68,40.9,10.3,22.2,0.464,0.9,2.9,0.305,7.0,8.2,0.853,1.5,4.3,5.9,5.0,1.7,0.6,3.2,28.5,25.3
4,2000-01,Regular%20Season,1713,5,Vince Carter,1610612761,TOR,75,39.7,10.2,22.1,0.460,2.2,5.3,0.408,5.1,6.7,0.765,2.3,3.2,5.5,3.9,1.5,1.1,2.2,27.6,23.9

In [22]:
# rename Regular%20Season to Regular Season
df["Season_type"] = df["Season_type"].replace("Regular%20Season", "Regular Season")

In [23]:
# check
df["Season_type"].unique()

array(['Regular Season', 'Playoffs'], dtype=object)

In [24]:
# Save the updated df back to the same file
df.to_excel(file_path, index=False)